In [ ]:
import  pandas as  pd
df = pd.read_csv("netflix_titles.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [ ]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [ ]:
df.shape

(8807, 12)

In [ ]:
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
missing = (df.isnull().sum()/len(df))*100
missing.sort_values(ascending=False)

director        29.908028
country          9.435676
cast             9.367549
date_added       0.113546
rating           0.045418
duration         0.034064
show_id          0.000000
type             0.000000
title            0.000000
release_year     0.000000
listed_in        0.000000
description      0.000000
dtype: float64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
# now data profiing

In [ ]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [ ]:
df['country'].nunique()

748

In [ ]:
df['listed_in'].nunique()

514

In [ ]:
df['listed_in'].value_counts()

listed_in
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
                                                   ...
Action & Adventure, Cult Movies                       1
Action & Adventure, Comedies, Music & Musicals        1
Classic Movies, Horror Movies, Thrillers              1
Children & Family Movies, Classic Movies, Dramas      1
Cult Movies, Dramas, Thrillers                        1
Name: count, Length: 514, dtype: int64

In [ ]:
df['rating'].nunique()

17

In [ ]:
df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [ ]:
# data cleaning

In [52]:
print(df['date_added'].dtype)

object

In [54]:
df['date_added']

0       September 25, 2021
1       September 24, 2021
2       September 24, 2021
3       September 24, 2021
4       September 24, 2021
               ...
8802     November 20, 2019
8803          July 1, 2019
8804      November 1, 2019
8805      January 11, 2020
8806         March 2, 2019
Name: date_added, Length: 8807, dtype: object

In [56]:
df['date_added'] = pd.to_datetime(df['date_added'])

ValueError: time data " August 4, 2017" doesn't match format "%B %d, %Y", at position 1442. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [58]:
df['date_added'].iloc[1442]

'January 4, 2021'

In [61]:
print(repr(df['date_added'].iloc[1442]))

'January 4, 2021'

In [63]:
df['date_added'] = df['date_added'].str.strip()
df['date_added'] = pd.to_datetime(df['date_added'])

AttributeError: Can only use .str accessor with string values!

In [65]:
df['date_added'] = pd.to_datetime(
    df['date_added'].astype(str).str.strip(),
    errors='coerce'
)

In [67]:
df.dtypes

show_id                 object
type                    object
title                   object
director                object
cast                    object
country                 object
date_added      datetime64[ns]
release_year             int64
rating                  object
duration                object
listed_in               object
description             object
dtype: object

In [69]:
# data cleaning

df['date_added'] = pd.to_datetime(df['date_added'])

In [71]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [72]:
# feature eng

In [74]:
df['year_added'] = df['date_added'].dt.year

In [75]:
df['month_added'] = df['date_added'].dt.month_name()

In [76]:
df['day_added'] = df['date_added'].dt.day_name()

In [77]:
df[['date_added','year_added','month_added']].head()

  date_added  year_added month_added
0 2021-09-25      2021.0   September
1 2021-09-24      2021.0   September
2 2021-09-24      2021.0   September
3 2021-09-24      2021.0   September
4 2021-09-24      2021.0   September

In [80]:
total_content  = len(df)
total_content

8807

In [81]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,day_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0,September,Saturday
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,September,Friday
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,September,Friday
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,September,Friday
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,September,Friday

In [86]:
movies = df[df['type']=='Movie'].shape[0]

movies

6131

In [93]:
tv_shows = df[df['type']=='tv_shows'].shape[0]

movies

6131

In [94]:
df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [97]:
df['country'].nunique()

748

In [100]:
df['rating'].mode()[0]

'TV-MA'

In [102]:
df['listed_in'].mode()

0    Dramas, International Movies
Name: listed_in, dtype: object

In [105]:
# now  some bussiness insights
import plotly.express as px

In [107]:
import plotly.express as px

fig = px.pie(
    df,
    names='type',
    title='Movies vs TV Shows'
)

fig.show()

In [110]:
country  = df['country'].value_counts().head(10)
country

country
United States     2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Egypt              106
Name: count, dtype: int64

In [113]:
fig = px.bar(
     x = country.index,
     y = country.values,
     title = 'Top 10 Countries'

)
fig.show()

In [117]:
yearly = (
    df['release_year']
    .value_counts()

)
yearly
fig = px.line(
    x=yearly.index,
    y=yearly.values,
    title='Netflix Content Growth'
)

fig.show()

In [122]:
ratings = df['rating'].value_counts().head(10)
ratings

fig = px.bar(
     x = ratings.index,
     y = ratings.values,
     title = 'Top 10 Ratings'

)
fig.show()

In [123]:
# statistics

In [135]:
df['release_year'].mean()
(df['release_year'] == 2014).sum()
df[df['release_year'] == 2014]['type'].value_counts()

type
Movie      264
TV Show     88
Name: count, dtype: int64

In [126]:
df['release_year'].median()

2017.0

In [128]:
df['release_year'].mode()

0    2018
Name: release_year, dtype: int64

In [136]:
df['release_year'].var()

77.78026646107675

In [138]:
df['release_year'].std()

8.819312130834057

In [139]:
# cross tab

In [145]:
pd.crosstab(
    df['type'],
    df['rating']
)

rating,66 min,74 min,84 min,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
type,,,,,,,,,,,,,,,,,
Movie,1,1,1,41,3,75,287,490,797,1427,126,2062,540,131,139,5,3
TV Show,0,0,0,0,0,5,0,0,2,733,94,1145,323,176,195,1,0

In [147]:
pd.crosstab(
    df['country'],
    df['type']
)

type                                                Movie  TV Show
country
, France, Algeria                                       1        0
, South Korea                                           0        1
Argentina                                              38       18
Argentina, Brazil, France, Poland, Germany, Den...      1        0
Argentina, Chile                                        2        0
...                                                   ...      ...
Venezuela                                               1        0
Venezuela, Colombia                                     1        0
Vietnam                                                 7        0
West Germany                                            1        0
Zimbabwe                                                1        0

[748 rows x 2 columns]

In [148]:
# pivot table analysis

In [150]:
pd.pivot_table(
    df,
    index='type',
    values='show_id',
    aggfunc='count'
)

         show_id
type
Movie       6131
TV Show     2676

In [152]:
pd.pivot_table(
    df,
    index='rating',
    values='release_year',
    aggfunc='mean'

)

          release_year
rating
66 min     2015.000000
74 min     2017.000000
84 min     2010.000000
G          1997.804878
NC-17      2015.000000
NR         2010.912500
PG         2008.428571
PG-13      2009.314286
R          2010.471840
TV-14      2013.655556
TV-G       2015.745455
TV-MA      2016.661678
TV-PG      2013.529548
TV-Y       2017.159609
TV-Y7      2015.508982
TV-Y7-FV   2014.833333
UR         1999.333333

In [156]:
pd.pivot_table(
    df,
    index='rating',
    values='release_year',
    aggfunc=['mean' , 'max'  , 'min']
)

                 mean          max          min
         release_year release_year release_year
rating
66 min    2015.000000         2015         2015
74 min    2017.000000         2017         2017
84 min    2010.000000         2010         2010
G         1997.804878         2020         1956
NC-17     2015.000000         2018         2013
NR        2010.912500         2018         1958
PG        2008.428571         2021         1973
PG-13     2009.314286         2021         1955
R         2010.471840         2021         1962
TV-14     2013.655556         2021         1925
TV-G      2015.745455         2021         1954
TV-MA     2016.661678         2021         1945
TV-PG     2013.529548         2021         1943
TV-Y      2017.159609         2021         1992
TV-Y7     2015.508982         2021         1981
TV-Y7-FV  2014.833333         2018         2012
UR        1999.333333         2016         1974

In [158]:
# grop by analysis

In [162]:
df.groupby('year_added')['show_id'].count()

year_added
2008.0       2
2009.0       2
2010.0       1
2011.0      13
2012.0       3
2013.0      11
2014.0      24
2015.0      82
2016.0     429
2017.0    1188
2018.0    1649
2019.0    2016
2020.0    1879
2021.0    1498
Name: show_id, dtype: int64

In [164]:
df.groupby('type')['show_id'].count()

type
Movie      6131
TV Show    2676
Name: show_id, dtype: int64

In [167]:
df.groupby('type')['release_year'].mean()

type
Movie      2013.121514
TV Show    2016.605755
Name: release_year, dtype: float64

In [169]:
df['director'].value_counts().head(10)

director
Rajiv Chilaka             19
Raúl Campos, Jan Suter    18
Suhas Kadav               16
Marcus Raboy              16
Jay Karas                 14
Cathy Garcia-Molina       13
Martin Scorsese           12
Youssef Chahine           12
Jay Chapman               12
Steven Spielberg          11
Name: count, dtype: int64

In [171]:
top_dir = df['director'].value_counts().head(10)

fig = px.bar(
    x=top_dir.values,
    y=top_dir.index,
    orientation='h',
    title='Top Directors'
)

fig.show()

In [173]:
# 📌 Executive Summary

## Key Findings:-

# - Netflix catalog contains 6,131 Movies and 2,676 TV Shows.
# - Movies account for nearly 70% of total content.
# - United States contributes the highest number of titles.
# - India ranks second in content production.
# - Netflix experienced rapid growth after 2016.
# - TV-MA is the most common content rating.
# - Drama-based content dominates the platform.

In [ ]:
# ## Final Conclusion

# Netflix has evolved into a global streaming platform with a strong movie-focused catalog, significant international content investments, and rapid content expansion after 2016. The platform's strategy appears to focus on globally appealing, mature, and drama-oriented content.